/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frequency_sweeper.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4d26b7ca0ba4b76b18dc758ee1f01511)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/spectre/frequency_sweeper.h>
// pydoc.h is automatically generated in the build directory
#include <frequency_sweeper_pydoc.h>

void bind_frequency_sweeper(py::module& m)
{

    using frequency_sweeper    = ::gr::spectre::frequency_sweeper;


    py::class_<frequency_sweeper, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<frequency_sweeper>>(m, "frequency_sweeper", D(frequency_sweeper))

        .def(py::init(&frequency_sweeper::make),
           py::arg("min_freq") = 9.0E+7,
           py::arg("max_freq") = 1106,
           py::arg("hop_freq") = 2.0E+6,
           py::arg("dwell_time") = 0.20000000000000001,
           py::arg("sample_rate") = 2.0E+6,
           py::arg("retune_cmd_name") = "freq",
           py::arg("input_type") = "fc32",
           D(frequency_sweeper,make)
        )
        



        ;




}








